apiVersion: v1
kind: Service
metadata:
  name: e-recrutement
  labels:
    app: e-recrutement
spec:
  type: NodePort
  ports:
  - port: 5000  # Use the fixed port
    targetPort: 5000  # Use the fixed port
    nodePort: 31000  # Optional: Specify a port between 30000-32767
  selector:
    app: e-recrutement